### ISSUE TITLE
Error "this class is not key value coding-compliant for the key" when using XIBs inside resource bundles

### ISSUE THREAD

**Issue by acecilia** [bazel-ios/rules_ios#113]
Hi:

I have been trying to debug this issue, but with little success. 

What I did:
1. Take the example `tests/ios/frameworks/target-xib` from this repository and copy it to `tests/ios/frameworks/target-xib-resource-bundle`
2. Modify the `BUILD.bazel` file to use a resource bundle
3. Update the source code to point to the right resource bundle when reading the XIB

When running the test from the example, the resource bundle is found, and the XIB is also found. But after that I am getting the error: `<unknown>:0: error: -[TargetXIBTestsLib.CustomViewTests testCustomView] : failed: caught "NSUnknownKeyException", "[<UIView 0x7f8d9fc6de50> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key label."`

Find the code with the failing test here: https://github.com/bazel-ios/rules_ios/pull/112
To try it out, just run `git clone https://github.com/acecilia/rules_ios.git -b customModuleProviderBug && cd rules_ios && bazelisk test --apple_platform_type=ios //tests/ios/frameworks/target-xib-resource-bundle:TargetXIBTests`

Thanks :)

**Comment by acecilia** [comment]
Issue may be related with the call to `ibtool`. From `man ibtool`:

```
       --module moduleName
              Specifies  the  module  name  to include in applicable custom class names at runtime. The module name should match the PRODUCT_MODULE_NAME build
              setting of the target for which the Interface Builder document is being compiled. This option is required for compiling any document  that  con-
              tains an object whose custom class is a Swift class and whose customModuleProvider attribute is set to target.
```

Reference: https://github.com/facebook/buck/blob/master/src/com/facebook/buck/apple/AppleBundleDescription.java#L435

**Comment by segiddins** [comment]
We don't use `customModuleProvider` so I'm not surprised it's not working -- probably need to plumb the module name through to the precompiled_resource_bundle target somehow

**Comment by acecilia** [comment]
Some more information, to be used as a future reference:

* The command line tool used for compiling storyboards, nibs and xibs is `ibtool`. Running `man ibtool` it is possible to see that the swift module is passed as a parameter:
    ```
    --module moduleName
        Specifies the module name to include in applicable custom class  names  at  runtime.  The  module  name
        should  match the PRODUCT_MODULE_NAME build setting of the target for which the Interface Builder docu-
        ment is being compiled. This option is required for compiling any  document  that  contains  an  object
        whose custom class is a Swift class and whose customModuleProvider attribute is set to target.
    ```
    Such swift module is used when the storyboard, nib or xib contains `customModuleProvider="target"`.

* The command line tool used of compiling CoreData models is `momc`. Running `xcrun momc -h ` it is possible to see that the swift module is passed as a parameter (seems to be the `--module` parameter):
    ```
    usage: momc --sdkroot=<path> [--appletvos-deployment-target] [--iphoneos-deployment-target] 
    [--macosx-deployment-target] [--watchos-deployment-target] [--module <module>]
     [--print-diagnostic-categories] [--no-warnings] [--no-inverse-relationship-warnings] 
    [--no-max-property-count-warnings] [--no-delete-rule-warnings] [--dump-models] source destination
    ```
    Such swift module seems to be used only when the CoreData model sets "Current Product Module" for its Module property.
