### ISSUE TITLE
Documentation on how to best consume existing xcconfig files using fetch_default_xcconfig?

### ISSUE THREAD

**Issue by tinder-maxwellelliott** [bazel-ios/rules_ios#149]
Hello There,

Thanks for this wonderful ruleset, I am excited to see a very large application successfully using these rules to build 😄 . I have a question about how to consume existing xcconfig files. I see in the documentation references to `default_xcconfig_name ` and `fetch_default_xcconfig`, I have set `default_xcconfig_name` and I am now told to implement `fetch_default_xcconfig`, is there an example of this I can refer to? Thanks!

**Comment by thiagohmcruz** [comment]
Hi @tinder-maxwellelliott take a look at how [cocoapods-bazel](https://github.com/bazel-ios/cocoapods-bazel) creates `DEFAULT_XCCONFIGS ` in `default_xcconfigs.bzl` [here](https://github.com/bazel-ios/cocoapods-bazel/blob/master/lib/cocoapods/bazel.rb#L68)

Essentially you want `fetch_default_xcconfig ` to be able to select a dict of `xcconfig`s for each possible value of `default_xcconfig_name `

**Comment by tinder-maxwellelliott** [comment]
Got it, so there is no way to really read an exiting xcconfig file. I need to convert those into dictionaries to make them work with rules_ios?

**Comment by thiagohmcruz** [comment]
Right, at the moment you'd have to parse the `*.xcconfig` files (using [Xcodeproj](https://github.com/CocoaPods/Xcodeproj) for example) and put them in a hash and then override `fetch_default_xcconfig` to get the correct dicts for each `default_xcconfig_name` as described [here](https://github.com/bazel-ios/rules_ios/blob/256dd04107bc98e50ce4bbc2c85dad2b7bef677b/rules/library.bzl#L177)

I get your point though, it would be nice to simply give the `*.xcconfig` files and let the rules take care of the rest 🤔

**Comment by tinder-maxwellelliott** [comment]
Thanks for the advice. I think I have a path forward using Xcodeproj.

**Comment by thiagohmcruz** [comment]
K! Let me know if I can help with anything else 👍

**Comment by tinder-maxwellelliott** [comment]
Seeing another issue here:

when using the following method to fetch xcconfigs

```python
def fetch_xcconfig(name, library_tools, default_xcconfig_name, **kwargs):
    return {"test": "something"}
```

```terminal
ERROR: Traceback (most recent call last):
        File "/Users/maxwellelliott/Tinder/tinder_ios/Projects/Modules/Domain/Recommendations/BUILD", line 239, column 16, in <toplevel>
                apple_framework(
        File "/private/var/tmp/_bazel_maxwellelliott/db37ab0e01ac1d9a8e5ea282dd04a720/external/build_bazel_rules_ios/rules/framework.bzl", line 26, column 28, in apple_framework
                library = apple_library(name = name, **kwargs)
        File "/private/var/tmp/_bazel_maxwellelliott/db37ab0e01ac1d9a8e5ea282dd04a720/external/build_bazel_rules_ios/rules/library.bzl", line 401, column 66, in apple_library
                copts_by_build_setting = copts_by_build_setting_with_defaults(xcconfig, fetch_default_xcconfig, xcconfig_by_build_setting)
        File "/private/var/tmp/_bazel_maxwellelliott/db37ab0e01ac1d9a8e5ea282dd04a720/external/build_bazel_rules_ios/rules/library/xcconfig.bzl", line 286, column 54, in copts_by_build_setting_with_defaults
                xcconfig_with_defaults[xc_build_setting] = value
Error: trying to mutate a frozen dict value
```

**Comment by segiddins** [comment]
That dict might need to be copied somewhere? If you figure out where, feel free to send a PR
