### ISSUE TITLE
Example on how to test apple_library inside of an ios_application rule

### ISSUE THREAD

**Issue by tinder-maxwellelliott** [bazel-ios/rules_ios#154]
Hello there,

I am looking to run tests against a ios_application target defined like so:

```
ios_application(
    name = "SomeApp",
    swift_objc_bridging_header = "SomeApp-Bridging-Header.h",
    srcs = glob(["**/*.m", "**/*.h", "**/*.swift"]),
    bundle_id = "com.app.SomeApp",
    minimum_os_version = "11.0",
    resources = [
        "//Projects/SomeApp:SomeAppAssets"
    ],
    entitlements = "//Projects/SomeApp:SomeAppEntitlements",
    infoplists = [
        ":SomeAppPlist"
    ],
    deps = [
        "ManyDeps"
    ]
)
```

How can I run tests against the underlying `apple_library` target in this rule? I would rather not use `apple_framework` here given no-one should ever import `SomeApp`.

**Comment by segiddins** [comment]
https://github.com/bazel-ios/rules_ios/tree/master/tests/ios/unit-test/test-imports-app is an example

**Comment by segiddins** [comment]
if you dont need to import `SomeApp`, you can put it as the `test_host` in your `ios_unit_test` without further changes

**Comment by tinder-maxwellelliott** [comment]
In this case I need to import the module, what is your guidance to
accomplish this?

**Comment by tinder-maxwellelliott** [comment]
Turned out to be an issue on my side, closing
