### ISSUE TITLE
Seeing symbol redefinition issues when using a bridging header

### ISSUE THREAD

**Issue by tinder-maxwellelliott** [bazel-ios/rules_ios#179]
Hello There,

I am running into issues with duplicate symbols when using a `swift_objc_bridging_header` in an `ios_application` rule. I have a branch here that showcases the issue when running `//tests/ios/unit-test/test-imports-app:TestImports-Unit-Tests`

https://github.com/bazel-ios/rules_ios/commit/01df46d225e11af057e0496e1739150a9265b265

Any help is appreciated!

**Comment by segiddins** [comment]
Can you give https://github.com/bazel-ios/rules_ios/pull/180 a try?

**Comment by tinder-maxwellelliott** [comment]
It looks like this solves the issue at hand, commenting in #180 about adding more complexity to the test setup

**Comment by tinder-maxwellelliott** [comment]
Update: This does not work when testing the target with a unit test target that uses a bridging header
