### ISSUE TITLE
Redundant `swift_library` builds when using apple_framework and ios_application

### ISSUE THREAD

**Issue by jerrymarino** [bazel-ios/rules_ios#184]
When using `rules_ios`, I noticed that there's redundant different builds of a `swift_library`.

```
apple_framework(name = "fw", ..)
ios_application(name="app", deps=["fw"])
```

When running the build, there will be 2 swiftmodules built ( 1 per the app, and 1 per the framework )
```
bazel build app fw
```

Additionally it builds 2x of all the transitive swift libraries and also causes issues with cache hits.

**Comment by jerrymarino** [comment]
When a `swift_library` is a dep of `ios_application`, it's getting `apple_common.multi_arch_split` and this doesn't happen when it's a dep of an `apple_framework`. Consequently, this nets a different output directory hash e.g. ( `ST-$hash` ).

`apple_split_cpu=` is factored into the output directory suffix due to the latter use of `apple_common.multi_arch_split`. This provider seems incompatible with the way that `rules_ios` e.g. the rules don't have a `minimum_os_version` or `platform_type`, but a dictionary of `platform` -> `min_version` .

Originally it looked like this might be related to (  https://github.com/bazelbuild/bazel/issues/12171 ), but I'm consistently getting different output hashes, ones that don't include `apple_split_cpu`.

Perhaps  #186 is related to this - resolving differences with `apple_common.multi_arch_split`

**Comment by jerrymarino** [comment]
@amberdixon I have tested this out in more situations and the good news is that it it's been happening prior to Bazel 3.4 - I suspect it's a different issue than  bazelbuild/bazel#12171 which started happening on 3.5.

I was wondering if you have an example of how  bazelbuild/bazel#12171 impacts rules_ios? It seems somewhat related!

**Comment by amberdixon** [comment]
Hello! I tried to test out this behavior in rules_ios as well .. perhaps I made a mistake, here's what I did:

1. I made the following change to tests/ios/app/BUILD.bazel, to make sure that App depends on SwiftLib. THis way we should be able to reproduce this issue ... because both App and the SwiftLib framework will depend  on the swift_library target named SwiftLib.
```
diff --git a/tests/ios/app/BUILD.bazel b/tests/ios/app/BUILD.bazel
index ed5c37c..19b3754 100644
--- a/tests/ios/app/BUILD.bazel
+++ b/tests/ios/app/BUILD.bazel
@@ -55,6 +55,7 @@ ios_application(
         ":FW",
         ":FW2",
         ":OnlySources",
+        ":SwiftLib",
     ],
 )
 ```

2. Run `bazelisk build tests/ios/app:App`
3. Run `bazelisk build tests/ios/app:SwiftLib`
4. Notice that there are two swiftmodules created!
```
~/Development/rules_ios master * ls -lt bazel-out/applebin_ios-ios_x86_64-dbg-ST-*/bin/tests/ios/app/SwiftLib.swiftmodule
-r-xr-xr-x  1 amberdixon  wheel  13580 Jan 12 19:33 bazel-out/applebin_ios-ios_x86_64-dbg-ST-7bf874b56ea0/bin/tests/ios/app/SwiftLib.swiftmodule
-r-xr-xr-x  1 amberdixon  wheel  13580 Jan 12 19:32 bazel-out/applebin_ios-ios_x86_64-dbg-ST-36e46a5aeba1/bin/tests/ios/app/SwiftLib.swiftmodule
```
5. Run cquery to see the different configurations SwiftLib is getting built in:
```
~/Development/rules_ios master *  bazelisk cquery tests/ios/app:SwiftLib
INFO: Analyzed target //tests/ios/app:SwiftLib (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
//tests/ios/app:SwiftLib (d7756e3)
//tests/ios/app:SwiftLib (f458991)
INFO: Elapsed time: 0.098s
INFO: 0 processes.
INFO: Build completed successfully, 0 total actions
```
6. Notice that the configuration don't differ, other than the "affected by starlark transition" key:
```
~/Development/rules_ios master * bazelisk config d7756e3 f458991
INFO: Displaying diff between configs d7756e3 and f458991
Displaying diff between configs d7756e3 and f458991
FragmentOptions com.google.devtools.build.lib.analysis.config.CoreOptions {
  affected by starlark transition: [apple configuration distinguisher, apple_platform_type, apple_split_cpu, cpu, ios_minimum_os], [apple configuration distinguisher, apple_platform_type, cpu, ios_minimum_os]
  transition directory name fragment: ST-36e46a5aeba1, ST-7bf874b56ea0
}
```

That makes me think this is another example of bazelbuild/bazel#12171

**Comment by jerrymarino** [comment]
Ah great, thanks for the context! Yeah that's what I was seeing as well - `apple_split_cpu` is missing from rules iOS configuration.

The main root cause of this I have traced down is the lack of multi platform transition be fixed in the linked PR(s) 🥳
