### ISSUE TITLE
ios_unit_test doesn't support flaky=True

### ISSUE THREAD

**Issue by zachgray-slack** [bazel-ios/rules_ios#243]
Was surprised to find this issue when marking an `ios_unit_test` as [flaky](https://docs.bazel.build/versions/master/be/common-definitions.html#common-attributes-tests).

At a glance this is due to the flaky kwarg passing through into the library rules which don't support it, because it's not in the list of test args (`_IOS_TEST_KWARGS`) that are popped; this is a trivial fix which I'll send a patch for, but I was curious if there's some issue at play here, since this one seems likely to have been caught by now.

**Comment by erikkerber** [comment]
@zachgray-slack OK to close?
