### ISSUE TITLE
[xcodeproj] Unable to use click to test chevrons in unit tests

### ISSUE THREAD

**Issue by tinder-maxwellelliott** [bazel-ios/rules_ios#283]
Hello rules_ios,

I have been facing issues locally getting "Click to test" working in generated Xcode projects, what I mean by this is these icons in tests 

<img width="154" alt="Screen Shot 2021-07-29 at 12 34 17 PM" src="https://user-images.githubusercontent.com/56700854/127558387-f0bfe1e0-1707-489f-bda6-646c2f0d023c.png">

When I click that I get this output

```terminal
Test Suite 'Selected tests' passed at 2021-07-29 12:37:13.527.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.002) seconds
```

I am using a .bazelrc that is basically identical to what is in this repo. I am doing some ENV cleaning via a Bazel wrapper script unsure if that is what is causing the issue or not.

**Comment by thiagohmcruz** [comment]
Hi @tinder-maxwellelliott thx for catching this! Would you be able to share a small repro project with this behaviour? Any hint in Xcode's build log?

**Comment by tinder-maxwellelliott** [comment]
A question I have off the bat is, are ENV variables used to control what is launched? If so I do worry that our ENV filtering is taking out variables that are needed

**Comment by tinder-maxwellelliott** [comment]
Okay I took out my custom TestHost, used the built in one, removed my ENV cleaning, removed all bazelrc's to the bare minimum and still not dice. Going to keep hunting around for anything out of place

**Comment by thiagohmcruz** [comment]
cc @dostrander have you seen this before?

**Comment by tinder-maxwellelliott** [comment]
Aha! I got it! These two must match:

```python
ios_unit_test(
    name = "MyModule_Unit_Tests",
    module_name = "MyModule_Unit_Tests",
```

**Comment by gyfelton** [comment]
> ```python
> ios_unit_test
> ```

This sounds like a bug where a place that should use module_name is using `name` instead? @tinder-maxwellelliott I will try to repro using existing test case but changing the name/module name

**Comment by gyfelton** [comment]
Ha the trick is `_` is equiv. to `-`, If I open Test-Imports-App-Project.xcodeproj under `tests/ios/xcodeproj` and run tests by adding the test scheme, i got testes executed fine. But if I make the module_name diff by adding `2` in the end, the tests now fails. That test whose target name being `TestImports-Unit-Tests` has a 'same' module name `TestImports_Unit_Tests` but we should really make sure `TestImports_Unit_Tests2`  also works?

**Comment by gyfelton** [comment]
Here is. a repro branch: https://github.com/bazel-ios/rules_ios/tree/elton/reproduce-case-no-test-run
