### ISSUE TITLE
macro to compile

### ISSUE THREAD

**Issue by cdoky** [bazel-ios/rules_ios#290]
![image](https://user-images.githubusercontent.com/626401/128458581-c520fdf9-e692-4b2b-8b13-729e6827bb37.png)

This library requires a macro to compile, but where should I add it?

**Comment by justinseanmartin** [comment]
There is a `objc_copts` optional argument used in apple_library, defined at rules/library.bzl#401. 

If you use cocoapods-bazel plugin, it should handle creating the BUILD.bazel file for you with these parameters set, though I'm not 100% certain it plumbs this implicit cflag through. It does allow you to specify your own wrapper for apple_library where you could add whatever logic for inserting the cflags you need.

**Comment by cdoky** [comment]
@justinseanmartin Thanks
```bazel
apple_framework(
    name = "URLNavigator",
    srcs = glob(["Sources/**/*.swift"]),
    platforms = {"ios": "8.0"},
    sdk_frameworks = [
        "Foundation",
        "UIKit",
    ],
    swift_copts = [
        "-D",
        "COCOAPODS"
    ],
    swift_version = "5.0",
    visibility = ["//visibility:public"],
)
```

**Comment by justinseanmartin** [comment]
Yep, missed that it was swift flags in the original screenshot, but that's the one!

**Comment by Jacky-LinPeng** [comment]
I used swift_copts to add macros ineffectively， bazel 5.2.0,
