### ISSUE TITLE
In @tulsi//:tulsi/tulsi_aspects.bzl%tulsi_outputs_aspect aspect on apple_framework_packaging rule

### ISSUE THREAD

**Issue by cdoky** [bazel-ios/rules_ios#292]
bazel build success:
![image](https://user-images.githubusercontent.com/626401/128503692-fb9af23d-ec69-4c6b-83f2-502532571206.png)

but tulsi generated xcodeproj and run failed:
```shell
In @tulsi//:tulsi/tulsi_aspects.bzl%tulsi_outputs_aspect aspect on apple_framework_packaging rule
```

![image](https://user-images.githubusercontent.com/626401/128503561-cd087720-841d-45bc-b3b3-d3522ee37cf8.png)

**Comment by thiagohmcruz** [comment]
I don't think we can see the full error msg in your screenshot. Mind checking the build log in Xcode (cmd+9 then select the most recent build)?.

Also, `rules_ios` has it's own project generator and we prioritize building features using that as a reference. AFAIK folks haven't been testing to see how compatible with Tulsi things are.

Feel free to test it and let us know how it goes! See: https://github.com/bazel-ios/rules_ios/blob/master/rules/xcodeproj.bzl

**Comment by cdoky** [comment]
Sorry, I do't know how to generated project by rules_ios, 
Do we have a document for how you generated xcode project?

**Comment by thiagohmcruz** [comment]
You do that by invoking `bazel run` in `xcodeproj` targets, you can see a few examples here: https://github.com/bazel-ios/rules_ios/blob/master/tests/ios/xcodeproj/BUILD.bazel 

I just did a quick scan in the repo and I guess we don't have a more detailed documentation for that rule! We should definitely add it!

**Comment by thiagohmcruz** [comment]
cc @gyfelton in case what I said is false, AFAIK we don't have docs for that right?

**Comment by jerrymarino** [comment]
Based on the screenshot it looks like XCHammer related? I think rules_ios needs to be added into XCHammer and Tulsi still

**Comment by cdoky** [comment]
Thank you!
Use xcodeproj generated success!
But, how to fixed the info.plist?

```bazel
ios_application(
    name = "app",
    bundle_id = "cc.gle.app",
    srcs = glob([
        "iOSApp/*.swift",
    ]),
    resources = [
        "iOSApp/Base.lproj/LaunchScreen.storyboard",
    ],
    swift_version = "5.0",
    visibility = ["//visibility:public"],
    families = [
        "iphone",
        "ipad",
    ],
    minimum_os_version = "9.0",
    infoplists = [":iOSApp/Info.plist"],
    deps = [
]
)
```

https://github.com/bazel-ios/rules_ios/blob/8682f956e6668b18889e01c21a8ff4114fa88d7c/rules/xcodeproj.bzl#L708-L710

Need copy my `:iOSApp/Info.plist` into `"$BAZEL_STUBS_DIR/Info-stub.plist" `?

**Comment by jschear** [comment]
I believe the Info.plist used in the generated project is a stub/fake file included only to avoid errors in Xcode. The Info.plist referenced by your `ios_application` rule will still be used when building via the generated project.

**Comment by cdoky** [comment]
Finally use the latest version, run successfully!

**Comment by Jacky-LinPeng** [comment]
Not Working...，
<img width="864" alt="image" src="https://user-images.githubusercontent.com/15797691/179990741-c0f7cca3-e73a-408e-b3aa-d39a2997408d.png">

<img width="836" alt="image" src="https://user-images.githubusercontent.com/15797691/179990612-b5f5598f-a101-443c-9783-a360510204a6.png">

**Comment by Jacky-LinPeng** [comment]
> Finally use the latest version, run successfully!
> 
> ```
> xcodeproj(
>     name = "xcodeproj",
>     bazel_path = "bazelisk",
>     generate_schemes_for_product_types = ["application"],
>     include_transitive_targets = True,
>     infoplist_stub = "iOSApp/Info.plist",
>     project_name = "iOSApp",
>     deps = [
>         ":app",
>     ],
> )
> ```

老哥 有demo工程吗 发我参考学习下... 我也遇到同样的问题，build没问题，tulsi生成的工程用Xcode就死活无法编译通过，可难受了。。。 哈哈哈

**Comment by cdoky** [comment]
bazel-iOS的项目和tulsi两个不互通的, 你只能通过`bazel run xcodeproj`生成xcode项目文件然后运行

**Comment by Jacky-LinPeng** [comment]
> 

感谢大佬.... 
tulsi生成的工程有毒，就是无法编译，我觉得应该是tulsi对apple_framewok没做好兼容...

**Comment by cdoky** [comment]
> > 
> 
> 感谢大佬.... tulsi生成的工程有毒，就是无法编译，我觉得应该是tulsi对apple_framewok没做好兼容...

tulsi的那一套, 貌似只能用官方的规则~~
我现在已经不搞这个了,
