### ISSUE TITLE
[Apple Silicon] consider providing a way to plug add libswiftCompatibility51

### ISSUE THREAD

**Issue by jerrymarino** [bazel-ios/rules_ios#398]
Some device built deps will need this linked due to missing symbols, the Xcode toolchain contains them in `libswiftCompatibility51`

Until rules_ios gets an official flag, you can use:
```
common:arm64_simulator_use_device_deps --linkopt=-Wl,-weak-lswiftCompatibility51 
common:arm64_simulator_use_device_deps --linkopt=-L__BAZEL_XCODE_DEVELOPER_DIR__/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator
```

**Comment by keith** [comment]
Note you probably shouldn't pass the `-l` flag for this, since it's something that's only required if the object files request it, so the `-L` should be enough.

**Comment by jerrymarino** [comment]
Ah interesting! I wonder if that build was somehow picking up `swiftCompatibility51` either by auto-linking it or picking up a [module map include](https://clang.llvm.org/docs/Modules.html#includes-as-imports) somewhere? e.g. it tries to load `switCompatibility` but without the build you get a "library not found error" without the path?  Curious about your setup none the less 

For me I vaguely remembered needing to add both the path and as a library to link on Xcode 12 but will circle back on it.

cc ^ @zachgray-slack

**Comment by keith** [comment]
By autolinking:

```
% swiftc foo.swift -c -o foo.o -sdk /Applications/Xcode-13.2.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk -target arm64-apple-ios12.0  -module-name foo
% otool -l foo.o | grep Compat
  string #1 -lswiftCompatibility50
  string #1 -lswiftCompatibility51
  string #1 -lswiftCompatibilityDynamicReplacements
  string #1 -lswiftCompatibilityConcurrency
```
