### ISSUE TITLE
FrameworkA-Swift.h: fatal error: module 'ThirdParty' not found (when @import inside autogenerated swift header file)

### ISSUE THREAD

**Issue by acecilia** [bazel-ios/rules_ios#55]
Hey guys,

First of all, thanks for this repo, looks very promising!

I have a problem I am not able to solve, maybe you have an idea of what is going on. I have something like the following (this is a bit simplified, but will do for now):

```
apple_dynamic_framework_import(ThirdParty) -> This is a prebuilt swift framework with objc support
  |
swift_library(LibA) -> This includes swift code
  |
apple_framework(FrameworkA) -> This is a framework with mixed swift and objc
```

When  building `FrameworkA` (with the latest from `master` from this repo) I get the following error:

```
In file included from Path/to/FrameworkA/somefile.m:7:
./bazel-out/apl-ios_x86_64-dbg/bin/Path/to/FrameworkA-Swift.h:186:9: fatal error: module 'ThirdParty' not found
@import ThirdParty;
 ~~~~~~~^~~~~~~~~
1 error generated.
```

I have been trying to reproduce it with the `mixed-source` example you provide and replicating the hierarchy I mentioned here, but couldn't: in all my trials the exampled built successfully. I realized that in this case the generated `FrameworkA-Swift.h` file does not contain `@import ThirdParty;`.

So, why is it then that when I build my framework I end up finding `@import ThirdParty;` inside `FrameworkA-Swift.h`?

The closes I have come to troubleshooting the issue sounds like https://bugs.swift.org/browse/SR-7051 and https://paul-samuels.com/blog/2018/01/14/swift-static-library-in-objective-c/, where they mention a very similar problem. The author solves it [here](https://paul-samuels.com/blog/2018/01/14/swift-static-library-in-objective-c/#step-4---create-a-modulemap).

Despite reading the linked blogs, I am out of ideas about how to approach this at the moment. Any help would be super welcome.

Thanks :)

**Comment by acecilia** [comment]
I finally managed to reproduce the problem in a standalone small project: https://github.com/acecilia/rules_ios/tree/mixed-source-module-failure

Just clone and run:

```
bazel build tests/mixed-source-import-swift/ios:MixedSourceFramework
```

**Comment by segiddins** [comment]
Try making `SwiftLibrary` an `apple_framework`, rather than a `swift_library`

**Comment by acecilia** [comment]
@segiddins thanks for your response :)

I did that, but the error persists. It even gets more interesting, because the error also happens if you swap `swift_library` with a swift binary:

```
apple_framework(
  name = "InputMask",
  vendored_dynamic_frameworks = ["Carthage/build/iOS/InputMask.framework"],
  visibility = ["//visibility:public"],
)
```

I updated the sample project with a new example: an `apple_framework` mixed source depending on an `apple_framework` swift precompiled binary (with this error happening): https://github.com/acecilia/rules_ios/tree/mixed-source-module-failure/tests/mixed-source-import-swift-framework/ios

Apparently what is going on is that:
- The `MixedSourceFramework-Swift.h` is generated. 
- This header contains `@import Dependency`: the compiler decides when to add such import based on reasons not very clear to me, but partially explained [here](https://bugs.swift.org/browse/SR-7051).
- When the compiler sees `@import` it expects that a corresponding module-map with the content:

```
module "Dependency" {
  header "Dependency-Swift.h"
}
```
is passed using some of the compiler flags `-fmodule-map-file` or `-fprebuilt-module-path` (this flags are to modules what `FRAMEWORK_SEARCH_PATHS` is to frameworks, seems like). To my knowledge this is not happening, as you can see here: https://github.com/bazel-ios/rules_ios/blob/master/rules/library.bzl#L514

Thus, the error `module not found`.

**Comment by acecilia** [comment]
I can confirm that if you add the following line inside `library.bzl`:

```
    objc_copts += [
        "-fmodules",
        "-fmodule-name=%s" % module_name,
        "-fmodule-map-file=/Users/user/Desktop/module.modulemap", # <=== In this line I am passing the path to the modulemap of `SwiftLibrary`
        "-gmodules",
    ]
```
And you have the header next to it:

```
/Users/user/Desktop/module.modulemap
/Users/user/Desktop/SwiftLibrary-Swift.h
```
The build succeeds.

**Comment by acecilia** [comment]
Also, if you build source code (not prebuilt binaries), and all of it is using `apple_framework` (not `swift_library`), and you depend on:
- https://github.com/bazelbuild/rules_swift.git: `657eda57a097980848dbb3c880b94faeddaa3cd1` (not what is currently set on master)
- https://github.com/bazel-ios/rules_ios.git (latest of this repo at the moment of writing): `8c0828c528561b0b7ea80fc8436276f65df4fd42`

It also builds successfully :)

**Comment by tinder-maxwellelliott** [comment]
Sorry to bring this very old thread back to life but I am experiencing this issue when using the [build cocoapods frameworks rule](https://github.com/bazel-ios/rules_ios/blob/master/docs/framework_builder_doc.md#build_cocoapods_frameworks). What is the best way to debug this issue?

I am on latest rules_ios and rules_swift

**Comment by segiddins** [comment]
The best way to debug is probably opening a PR with an example target that we can use as a test to repro the issue

**Comment by tinder-maxwellelliott** [comment]
I believe this is an error on my end, disregard my previous comment
