### ISSUE TITLE
Head File. Why cannot the relative path be imported but the absolute path can be imported

### ISSUE THREAD

**Issue by Jacky-LinPeng** [bazel-ios/rules_ios#551]
BUILD 
```
objc_library(
    name = "OCClasses",
    srcs = glob([
        "NewsApp/UrlGetViewController.m",
        "NewsApp/Login/**/*.m",
    ]),

    hdrs = glob([
	"NewsApp/**/*.h",
	"NewsApp/Login/**/*.h",
    ]),
    deps=[
        "//Vendor/NVActivityIndicatorView:NVActivityIndicatorView",
    ],

    sdk_frameworks = [
    	"ImageIO",
        "Accelerate",
        "QuartzCore",
        "CoreImage",
        "CoreData",
        "WebKit",
        "UIKit",
        "Security",
        "MobileCoreServices",
        "SystemConfiguration",
        "CoreGraphics",
        "AssetsLibrary",
        "MobileCoreServices",
        "Accelerate",
        "CoreFoundation",
        "CoreFoundation",
        "UIKit",
        "MapKit",
    ],
 
    visibility = [
     "//visibility:public"
    ],
)

```

it work fine
```
#import "NewsApp/Login/LoginVC.h"
#import "NewsApp/Login/Model/User.h"
```
but it get error
```
#import "LoginVC.h"
#import "User.h"
```
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/15797691/186679192-9cbf9d0a-344f-4543-aa68-70cef9f764ac.png">

I have found that using`COPTS ` or`includes ` can solve the problem of importing relative path, but it is a big code, I need to write a lot of file path information, is there a better way?

```
copts = [
     "-INewsApp/Login/",
     "-INewsApp/Login/Model/",
   ],

  or
  includes = [
     "NewsApp/Login/",
     "NewsApp/Login/Model/",
  ],
```

**Comment by jerrymarino** [comment]
Thanks for the issue! The Bazel rules ( e.g. `objc_library` ) aren't geared to work as iOS devs would expect or well supported in `bazel-ios` land. Did you consider to to replace `objc_library` with `apple_framework` in the example? That's how most of the test cases are working - you can see this in `tests/`

**Comment by Jacky-LinPeng** [comment]
> Thanks for the issue! The Bazel rules ( e.g. `objc_library` ) aren't geared to work as iOS devs would expect or well supported in `bazel-ios` land. Did you consider to replace `objc_library` with `apple_framework` in the example? That's how most of the test cases are working - you can see this in `tests/`

Thanks a million!! Your advice helped me a lot

**Comment by jerrymarino** [comment]
You got it - glad you've got it ironed out 👍 !
