### ISSUE TITLE
Transitive framework import causes release build fail

### ISSUE THREAD

**Issue by qyang-nj** [bazel-ios/rules_ios#569]
If we have an `apple_framework` transitively depends on `framework_import`, the build will fail with `--compilation_mode=opt`. In the following code, Module2 is not able to build. The same error will occur with `--features=swift.cacheable_swiftmodules`.

```
apple_dynamic_framework_import(
    name = "PrebuiltFramework",
)

apple_framework(
    name = "Module1",
    deps = [":PrebuiltFramework"],
)

apple_framework(
    name = "Module2",
    deps = [":Module1"],
)
```

With either `--compilation_mode=opt` or `--features=swift.cacheable_swiftmodules`, swift_library will stop passing `-serialize-debugging-options` to swiftc. Unfortunately, it seems we are relying on the search paths embedded in .swiftmodule for transitive framework imports. We should explicitly provide those search paths to the compiler.

**I have sample repro code  and steps [here](https://github.com/qyang-nj/BazelPlayground/tree/main/Issue0).**

**Comment by qyang-nj** [comment]
I have a fix in mind and will validate it and submit a PR.

**Comment by thiagohmcruz** [comment]
I guess we should re-open this give https://github.com/bazel-ios/rules_ios/pull/715

cc @mattrobmattrob @qyang-nj

**Comment by qyang-nj** [comment]
Thanks for adding the tests. I'll take a look at this again.
