### ISSUE TITLE
Update CI to use newer version of Xcode

### ISSUE THREAD

**Issue by qyang-nj** [bazel-ios/rules_ios#571]
Currently [the default Xcode version is 12.5.1](https://github.com/bazel-ios/rules_ios/blob/b1499fc08a7e4b7a7ba238fb4c9b089e6648ecbd/BUILD.bazel#L149) and that's what the CI is using as well.

However, Xcode 12.5.1 is no longer compatible with macOS Monterey. This causes reproducing a CI issue locally very difficult. 

![image](https://user-images.githubusercontent.com/6559265/192400466-e61c7640-c349-4c87-926c-389b8c9582d9.png)

**Comment by luispadron** [comment]
https://github.com/bazel-ios/rules_ios/pull/511

Should resolve this issue but its currently blocked.

**Comment by luispadron** [comment]
Closed by #580
