### ISSUE TITLE
[Error] Multiple files with the same name exists

### ISSUE THREAD

**Issue by emarashliev** [bazel-ios/rules_ios#614]
Hey guys! I'm not sure this check here is perfectly correct https://github.com/bazel-ios/rules_ios/blob/675767e64af77b44d9470946a7aee11407ff5f52/rules/framework.bzl#L131

I have a pod that uses this rule`load("@build_bazel_rules_ios//rules:framework.bzl", "apple_framework")`.
And it has quite an amount of C++ code inside, so I have two C++ .h files with the same name but they're in different folders, by my knowledge, this is perfectly okay, it builds in Xcode. Now I'm trying to migrate to Bazel and getting this error `[Error] Multiple files with the same name exists` because of those two C++ headers.

**Comment by mattrobmattrob** [comment]
Do you know where Xcode puts those headers of the same name in the resulting built `.framework` artifact? Do they both end up in the `Foo.framework/Headers` directory?

**Comment by emarashliev** [comment]
It was BUILD misconfiguration I suppose 🤦🏼‍♂️. I'll close the issue.
