### ISSUE TITLE
[rules_swift] override tarball deps to either use .zip or source checkouts 

### ISSUE THREAD

**Issue by jerrymarino** [bazel-ios/rules_ios#650]
There's an ongoing issue with tarballs on github: https://github.com/orgs/community/discussions/45830 and rules_swift points at many of the non-release URLs:
```
ERROR: An error occurred during the fetch of repository 'com_github_apple_swift_log':
ERROR: An error occurred during the fetch of repository 'com_github_apple_swift_nio_http2':
ERROR: An error occurred during the fetch of repository 'com_github_apple_swift_nio':
ERROR: An error occurred during the fetch of repository 'com_github_grpc_grpc_swift':
ERROR: An error occurred during the fetch of repository 'com_github_apple_swift_protobuf':
ERROR: An error occurred during the fetch of repository 'six':
ERROR: An error occurred during the fetch of repository 'com_github_apple_swift_nio_extras':
ERROR: An error occurred during the fetch of repository 'com_github_apple_swift_nio_transport_services':
```

We can use the zip URLs as a stopgap until there is a conclusion about what the resolution is - or just leave them as a zip. It isn't clear if they'll provide taballs back.

In `rules/repositories.bzl` - we should declare the depenecies upstream of `rules_swift` for now

**Comment by jerrymarino** [comment]
This was the offical comms from github that indicates they won't revert it:
https://github.com/bazel-contrib/SIG-rules-authors/issues/11#issuecomment-1409390654

**Comment by thiagohmcruz** [comment]
plot twist, revert on the way: https://github.com/bazel-contrib/SIG-rules-authors/issues/11#issuecomment-1409438954

**Comment by jerrymarino** [comment]
Yep, the nice thing is that moving to either zips or source is that it'd work in the case of this - though with github actively mitigating this I think it's probably file to close out for now and come up with a better plan longer term
