### ISSUE TITLE
Plist issue when objc_library depends on apple_framework

### ISSUE THREAD

**Issue by sergeykhliustin** [bazel-ios/rules_ios#659]
`ios_application` depends on `objc_library` which depends on `apple_framework`.
`apple_framework` link_dynamic is True and contains infoplist.

As a result ios_application tries to merge all plists in the tree
`Info.plist-root-control` contains:
```json
"plists": [
        "bazel-out/ios-sim_arm64-min13.0-applebin_ios-ios_sim_arm64-fastbuild-ST-1b700b3e3c9a/bin/Pods/FrameworkB/FrameworkB_InfoPlist.plist",
        "bazel-out/applebin_ios-ios_sim_arm64-fastbuild-ST-cda6179ccb9a/bin/_TestApp_iOS.0.info.plist",
        {
            "CFBundleIdentifier": "com.bazelpods.testapp"
        }
    ],
```
Example project https://github.com/sergeykhliustin/rules_ios_plist_issue

**Comment by mattrobmattrob** [comment]
I think the proper way to do this is just swap the `objc_library` rule out for `apple_framework` so it's `apple_framework` all the way down.

Any reason you aren't doing that?

**Comment by sergeykhliustin** [comment]
I'm writing another tool to convert CocoaPods to Bazel build files using `rules_ios`.
Now trying to make everything compatible with `rules_xcodeproj`.
But `apple_framework` which contains only headers or empty srcs generates empty `_objc` rules, so nothing in `bazel-out` where `rules_xcodeproj` fails.

Actually, I need something like xcode's "aggregate target" where I can specify vendored deps and some extra opts without sources. looks like `objc_library` is good for this

**Comment by mattrobmattrob** [comment]
I'd bet there's a lot more stuff that wouldn't work with this `objc_library => apple_framework` relationship as well.

The issue with `rules_xcodeproj` sounds like something it isn't yet handling since the Bazel build works with the avoidance of `objc_library`. Can you file a ticket there/figure out why it's fails when Bazel can build it?

**Comment by sergeykhliustin** [comment]
everything else works as expected, if `linkdynamic` is false, that's why I think it's an issue.
I think it's a good feature to have the ability to mix with native rules.
I'll close this but maybe you can point me to where `Info.plist-root-control` content generated, I'll try to fix this.

**Comment by mattrobmattrob** [comment]
`apple_framework`'s Info plist logic is here:

https://github.com/bazel-ios/rules_ios/blob/ea40a7b13dd1a29a454de2268a3799a65907501a/rules/framework.bzl#L54-L71

Then that's packaged up via `apple_framework_packaging` here:

https://github.com/bazel-ios/rules_ios/blob/ea40a7b13dd1a29a454de2268a3799a65907501a/rules/framework.bzl#L94-L95

And the implementation of `apple_framework_packaging` is here:

https://github.com/bazel-ios/rules_ios/blob/ea40a7b13dd1a29a454de2268a3799a65907501a/rules/framework.bzl#L908
