### ISSUE TITLE
`bazel build //tests/ios/xcframeworks/Basic:xcframeworks` is failing

### ISSUE THREAD

**Issue by qyang-nj** [bazel-ios/rules_ios#720]
This is on the latest master branch. `bazel build //tests/ios/xcframeworks/Basic:xcframeworks` is failing with the following error.
```
tests/ios/xcframeworks/Basic/Sources/Foo.swift:6:16: error: cannot find 'FooDynamic' in scope
    let foo1 = FooDynamic(num: 9000)
               ^~~~~~~~~~
tests/ios/xcframeworks/Basic/Sources/Foo.swift:9:16: error: cannot find 'FooStatic' in scope
    let foo2 = FooStatic(num: 9000)
               ^~~~~~~~~
Target //tests/ios/xcframeworks/Basic:xcframeworks failed to build
``` 

Similarly, `bazel build //tests/ios/xcframeworks/Basic:XCFrameworksApp` fails on M1 laptop or with `--cpu=ios_sim_arm64` option.
```
ld: 14 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error in child process '/usr/bin/xcrun'. 1
Target //tests/ios/xcframeworks/Basic:XCFrameworksApp failed to build
```

**Comment by luispadron** [comment]
So for `//tests/ios/xcframeworks/Basic:xcframeworks` you need to set `--apple_platform_type=ios`. Once #719 merges this should be as easy as `--config=ios` when building things under `tests/ios`.

For `` you need to run it like:

```sh
bazel build //tests/ios/xcframeworks/Basic:XCFrameworksApp --apple_platform_type=ios --features=apple.virtualize_frameworks
```

Just tried both on my M1 and they're building with the platform flag. It might be a bug though that `Basic:XCFrameworksApp` only works with VFS.
