### ISSUE TITLE
Unknown class in Interface Builder file

### ISSUE THREAD

**Issue by barbasevich** [bazel-ios/rules_ios#74]
I have a simple project [TestXIB](https://github.com/barbasevich/bazel-test-xib) with `CustomView.swift` and `CustomView.xib`.
xib file has `customClass="CustomView" customModule="TestXIB" customModuleProvider="target"` settings.

When I'm running unit tests and trying to instantiate `CustomView` from xib I get an error:
`Unknown class _TtC39TestXIBTests.__internal__.__test_bundle10CustomView in Interface Builder file.`

If I either switch from `apple_framework` to `swift_library` or remove `customModuleProvider="target"` from xib all works fine.

Any ideas on how to solve the issue using `apple_framework` without xib modification.?

**Comment by segiddins** [comment]
Ah yeah that could be it, good hunch
