### ISSUE TITLE
Cannot use latest rules_ios - missing arm64-to-sim, other dep errors 

### ISSUE THREAD

**Issue by jerrymarino** [bazel-ios/rules_ios#781]
Getting several new errors when trying to use the latest version of rules_ios. 

We see errors like:

>/private/var/tmp/_bazel_build/a38278faa597bf6d4e647970e120bcdb/external/build_bazel_rules_ios/rules/library/xcconfig.>bzl:21:12: GCC_DEBUG_INFORMATION_FORMAT: \"\" not a valid value, must be one of [\"dwarf\", \"dwarf-with-?>dsym\"]\nDEBUG: >/private/var/tmp/_bazel_build/a38278faa597bf6d4e647970e120bcdb/external/build_bazel_rules_ios/rules/library/xcconfig.>bzl:21:12: GCC_DEBUG_INFORMATION_FORMAT: \"\" not a valid value, must be one of [\"dwarf\", \"dwarf-with->dsym\"]\nERROR: Evaluation of subquery \"deps($roots)\" failed (did you want to use --keep_going?): preloading transitive >closure failed: no such package '@arm64-to-sim//': The repository '@arm64-to-sim' could not be resolved: Repository >'@arm64-to-sim' is not defined\nLoading: 4400 packages loaded\n   ....ages)">

**Comment by jerrymarino** [comment]
cc @luispadron it looks [like the PR](https://github.com/bazel-ios/rules_ios/commit/bf647f1bf4b7311d03248c4e533d13f3aa612c44) to add bzlmod has broken rules_ios in a few ways

**Comment by luispadron** [comment]
Will be fixed by #782
