### ISSUE TITLE
Failing .xcodeproj Tests on Xcode 14.2.0

### ISSUE THREAD

**Issue by AngelaGuardia** [bazel-ios/rules_ios#830]
**PROBLEM**
The CI pipeline seems to be broken. The `.xcodeproj Tests on Xcode 14.2.0` fail with the following [error](https://github.com/bazel-ios/rules_ios/actions/runs/7760573277/job/21167108765?pr=829):
```
/Users/runner/work/rules_ios/rules_ios/tests/ios/unit-test/test-imports-app/Header2.h:6:5: error: redefinition of enumerator 'AppErrorCodeUnknown'
```

**REPRO**
This is happening on new PRs (including a PR that just touches a file):
- https://github.com/bazel-ios/rules_ios/pull/829
- https://github.com/bazel-ios/rules_ios/pull/828
- https://github.com/bazel-ios/rules_ios/pull/827

**Comment by thiagohmcruz** [comment]
Taking a look. I'll try to find a way to make it pass to unblock folks while we root cause it.

**Comment by thiagohmcruz** [comment]
https://github.com/bazel-ios/rules_ios/pull/832

**Comment by thiagohmcruz** [comment]
Also, maybe focusing on bumping to Xcode 15 is a better use of our time if we decide to drop 14.x as part of that. But that's a separate discussion I guess.
