### ISSUE TITLE
Error When C++ include in CustomModuleMap

### ISSUE THREAD

**Issue by Detailscool** [bazel-ios/rules_ios#857]
In rules_ios/tests/ios/frameworks/mixed-source,  I try to make B.h public and I write #import “B.h” in CustomModuleMap.h,  comes this error:

<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/CustomModuleMap.h"
        ^
/private/var/tmp/_bazel_henry/e11db709b1242b3b39803cbacd605f76/rules_xcodeproj.noindex/build_output_base/execroot/__main__/custom-module-map/Sources/CustomModuleMap.h:2:9: note: in file included from /private/var/tmp/_bazel_henry/e11db709b1242b3b39803cbacd605f76/rules_xcodeproj.noindex/build_output_base/execroot/__main__/custom-module-map/Sources/CustomModuleMap.h:2:
#import "B.h"
        ^
/private/var/tmp/_bazel_henry/e11db709b1242b3b39803cbacd605f76/rules_xcodeproj.noindex/build_output_base/execroot/__main__/custom-module-map/Sources/B.h:3:10: error: 'vector' file not found
#include <vector>

What should I do to solve it ? Thx.

**Comment by mattrobmattrob** [comment]
Can you post the `git diff` from your changes to the example and the `bazel build` or `bazel test` command to replicate the failure you're seeing?
